# Some tutorials I used when getting started
#  https://man7.org/linux/man-pages/man1/tmux.1.html
#  https://github.com/ThePrimeagen/dev/blob/master/env/.config/tmux/tmux.conf
#  https://www.youtube.com/playlist?list=PLT98CRl2KxKGiyV1u6wHDV8VwcQdzfuKe
#  https://www.learnlinux.tv/learn-tmux-part-5-how-to-customize-tmux-and-make-it-your-own/

# Bind the prefix key
set-option -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

# Create a key to source the tmux-conf
bind-key r source-file ~/.config/tmux/tmux.conf \; display-message "tmux.conf was reloaded"

# Mouse Mode
set-option -g mouse on

# Status Options
set-option -g status-justify centre

# General Settings
set-option -g base-index 1
set-option -g pane-base-index 1
set-option -g renumber-windows on
set-option -g status-interval 3
set-option -g default-terminal "screen-256color"
set-option -ga terminal-overrides ",*256col*:Tc"

# Override find window. Call tmux-sessionizer
bind-key -r f run-shell "tmux neww tmux-sessionizer"

# # Use Alt-arrow keys without prefix key to switch panes
# bind -n M-Left select-pane -L
# bind -n M-Right select-pane -R
# bind -n M-Up select-pane -U
# bind -n M-Down select-pane -D

# No plugins right now
# # Plugin List
# set -g @plugin 'tmux-plugins/tpm'

# # set -g @plugin 'tmux-plugins/tmux-resurrect'    # Persist tmux sessions after computer restart
# # set -g @plugin 'tmux-plugins/tmux-continuum'    # Automatically saves sessions every 15 minutes

# # Ressurect
# # set -g @resurrect-capture-pane-contents 'on'

# # Initialize TPM - ALWAYS LAST
# run '~/.config/tmux/plugins/tpm/tpm'
